# Generated by Django 4.2.11 on 2024-03-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="status",
            field=models.IntegerField(
                choices=[(1, "success"), (2, "pending"), (3, "ignored")],
                default=2,
                verbose_name="status",
            ),
        ),
    ]
