# Generated by Django 4.2.11 on 2024-05-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_answercontacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="is_closed",
            field=models.BooleanField(default=False, verbose_name="is_closed"),
        ),
    ]
