# Generated by Django 4.2.11 on 2024-05-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_contactus_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactus",
            name="is_closed",
        ),
        migrations.RemoveField(
            model_name="contactus",
            name="is_seen",
        ),
        migrations.AlterField(
            model_name="contactus",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "مشاهده شده"),
                    (2, "درحال پردازش"),
                    (3, "رد شده"),
                    (4, "پاسخ داده شده"),
                    (5, "ّسته شده"),
                ],
                default=2,
                verbose_name="status",
            ),
        ),
    ]
