# Generated by Django 4.2.11 on 2024-05-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0010_remove_contactus_is_closed_remove_contactus_is_seen_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "مشاهده شده"),
                    (2, "درحال پردازش"),
                    (3, "رد شده"),
                    (4, "پاسخ داده شده"),
                    (5, "ّبسته شده"),
                ],
                default=2,
                verbose_name="status",
            ),
        ),
    ]
