# Generated by Django 4.2.11 on 2024-05-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_alter_contactus_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="status",
            field=models.IntegerField(
                choices=[
                    (2, "درحال پردازش"),
                    (3, "رد شده"),
                    (4, "پاسخ داده شده"),
                    (5, "ّبسته شده"),
                ],
                default=2,
                verbose_name="status",
            ),
        ),
    ]
