# Generated by Django 4.2.11 on 2024-04-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentNovin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "authority_id",
                    models.CharField(max_length=255, verbose_name="Authority"),
                ),
                (
                    "ref_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="ref id"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="amount",
                    ),
                ),
                (
                    "response_json",
                    models.JSONField(default=dict, verbose_name="response json"),
                ),
                (
                    "response_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="response code"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "در انتظار"),
                            (2, "پرداخت موفق"),
                            (3, "پرداخت ناموفق"),
                        ],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created date"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="updated date"),
                ),
            ],
        ),
    ]
