# Generated by Django 4.2.11 on 2024-03-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customerprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="media/images/profile/avatars/OIP.jfif ",
                upload_to="images/profile/avatars/",
                verbose_name="avatar image",
            ),
        ),
    ]
