# Generated by Django 4.2.11 on 2024-03-23 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_customerprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customerprofile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
