# Generated by Django 4.2.11 on 2024-03-23 20:32

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[accounts.validators.validate_iranian_cellphone_number], verbose_name='phone number'),
        ),
    ]
