# Generated by Django 4.2.11 on 2024-04-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=True, verbose_name="verified status"),
        ),
    ]
