# Generated by Django 4.2.11 on 2024-04-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ("created_date",),
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
            },
        ),
    ]
