# Generated by Django 4.2.11 on 2024-05-21 21:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default=None, max_length=40, verbose_name="title"),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="description"),
                ),
                ("brief_description", models.TextField(blank=True, null=True)),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="stock")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=10, verbose_name="price"
                    ),
                ),
                (
                    "discount_percent",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="discount percent",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        default=None,
                        max_length=40,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "نمایش"), (2, "عدم نمایش ")],
                        default=2,
                        verbose_name="status",
                    ),
                ),
                (
                    "famous_percent",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="famous percent"
                    ),
                ),
                ("avg_rate", models.FloatField(default=0, verbose_name="avg rate")),
                (
                    "image",
                    models.ImageField(
                        default="images/products/default_img/product-default.png",
                        upload_to="images/products",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "jfif"],
                                message="اپلود تصویر با پسوند“%(extension)s” مجاز نیست پسوند های مجاز jpg, png, jfif, jpeg",
                            )
                        ],
                        verbose_name="image",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="updated time"),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "product",
                "ordering": ("created_date", "updated_date"),
            },
        ),
        migrations.CreateModel(
            name="WishList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="updated time"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wish_list",
                        to="shop.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wish_list",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "WishList",
                "verbose_name_plural": "WishLists",
                "db_table": "wish_list",
                "ordering": ("created_date", "updated_date"),
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        default="images/products/default_img/product-default.png",
                        upload_to="images/products/many_image/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif"]
                            )
                        ],
                        verbose_name="file",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="updated time"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_image",
                        to="shop.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product image",
                "verbose_name_plural": "Product images",
                "db_table": "product_image",
                "ordering": ("created_date", "updated_date"),
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default=None, max_length=40, verbose_name="title"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        default=None,
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subs",
                        to="shop.productcategory",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product category",
                "verbose_name_plural": "Product categories",
                "ordering": ("created_date",),
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="shop.productcategory",
                verbose_name="category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
