# Generated by Django 4.2.11 on 2024-03-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_options_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/products/default_img/product-default.png', upload_to='images/products', verbose_name='image'),
        ),
    ]
