# Generated by Django 4.2.11 on 2024-03-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_product_brief_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                related_name="products",
                to="shop.productcategory",
                verbose_name="category",
            ),
        ),
    ]
