# Generated by Django 4.2.11 on 2024-03-27 07:49

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_product_discount_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="description"),
        ),
    ]
