# Generated by Django 4.2.11 on 2024-03-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='famous_percent',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='famous percent'),
        ),
    ]
