# Generated by Django 4.2.11 on 2024-04-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="avg_rate",
            field=models.FloatField(default=0, verbose_name="avg rate"),
        ),
    ]
