# Generated by Django 4.2.11 on 2024-05-08 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_productcategory_parent_remove_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subs",
                to="shop.productcategory",
                verbose_name="parent",
            ),
        ),
    ]
