# Generated by Django 4.2.11 on 2024-05-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_alter_productcategory_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_date",
            field=models.DateTimeField(verbose_name="created time"),
        ),
    ]
