# Generated by Django 4.2.11 on 2024-05-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_alter_product_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created time"),
        ),
    ]
