# Generated by Django 4.2.11 on 2024-05-29 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100, verbose_name="subject")),
                ("from_email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "to_email",
                    models.TextField(max_length=10000, verbose_name="to email"),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "منتشر شده"), (2, "ذخیره"), (3, "لغو شده")],
                        default=2,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="created date"),
                ),
                ("time_published", models.DateTimeField(verbose_name="time published")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_email",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
