# Generated by Django 4.2.11 on 2024-05-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_email", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupemail",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created date"),
        ),
    ]
