# Generated by Django 4.2.11 on 2024-04-12 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_zarin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payment.paymentzarin",
                verbose_name="payment zarin",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_zibal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payment.paymentzibal",
                verbose_name="payment zibal",
            ),
        ),
    ]
