# Generated by Django 4.2.11 on 2024-04-07 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0002_alter_coupon_discount_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="used_by",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="coupon_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="used by",
            ),
        ),
    ]
