# Generated by Django 4.2.11 on 2024-04-12 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_paymentnovin"),
        ("order", "0002_alter_order_payment_zarin_alter_order_payment_zibal"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_novin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payment.paymentnovin",
                verbose_name="payment novin",
            ),
        ),
    ]
