# Generated by Django 4.2.11 on 2024-04-15 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_order_payment_novin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[(1, "موفقیت امیز"), (2, "درحال پردازش"), (3, "لغو شده")],
                default=2,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="order.order",
                verbose_name="order",
            ),
        ),
    ]
