# Generated by Django 4.2.11 on 2024-04-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_coupon_used_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "processing"),
                    (2, "pending"),
                    (3, "shipping"),
                    (4, "delivered"),
                    (5, "cancelled"),
                ],
                default=2,
                verbose_name="status",
            ),
        ),
    ]
