# Generated by Django 4.2.11 on 2024-04-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_order_status_alter_orderitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price_default",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=10,
                verbose_name="total price default",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=10, verbose_name="total price"
            ),
        ),
    ]
