# Generated by Django 4.2.11 on 2024-04-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_alter_coupon_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="expired_date",
            field=models.DateTimeField(verbose_name="expired date"),
        ),
    ]
