# Generated by Django 4.2.11 on 2024-05-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_price_default",
        ),
    ]
