# Generated by Django 4.2.11 on 2024-05-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_remove_order_total_price_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_date",
            field=models.DateTimeField(verbose_name="created time"),
        ),
    ]
