# Generated by Django 4.2.11 on 2024-04-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_alter_coupon_expired_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
