# Generated by Django 4.2.11 on 2024-05-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_alter_order_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created time"),
        ),
    ]
